spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpatest
    username: root
    password: Qazwsx1-.
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    hibernate:
      ddl-auto: update
      event:
        merge:
          entity_copy_observer: allow
    show-sql: true
    database: mysql


